# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713c162090424bf9e168543d244ed53fca3a496d599ae5f3d663df8cad971485be1ad3b1ffaa327b202dd39b47baf2089406541512ae67fbac9e8a6413d03036

test:
  secret_key_base: 37e68417fbf5e078dda094d757b0f5d5931c5a0a6bac24fbad854d1bd7ac80e21420d6b2d6589bc9ea49117b4ec773e221ef1026890c1032231b0c79448cb3d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
